#!/bin/bash

choice=`printf "Shutdown\nLog Out\nReboot\nCancel" | dmenu -p "Operation"`
#echo $choice

case $choice in
	Shutdown)
		echo "case is $choice"
		shutdown -h now
		;;
	Reboot)
		echo "case is $choice"
		reboot
		;;
	"Log Out")
		echo "case is $choice"
		i3-msg exit
		;;

	*)
	;;
	
esac

